version: "3.7"

volumes:
  telraam_grafana_storage: {}
  prometheus_data: {}

services:
  timesync:
    build:
      context: timesync/
      dockerfile: Dockerfile
    network_mode: host
  prometheus:
    image: prom/prometheus:v2.35.0
    volumes:
      - ./prometheus/:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    network_mode: host
    depends_on:
      - blackbox
      - snmp
    # ports:
    #   - "9090:9090"
  snmp:
    build:
      context: snmp/
      dockerfile: Dockerfile
    network_mode: host
  blackbox:
    build:
      context: blackbox/
      dockerfile: Dockerfile
    network_mode: host
    # ports:
      # - "9115:9115"
  grafana:
    build:
      context: grafana
    user: "472"
    # depends_on:
    # - prometheus
    # Host network so grafana can query to localhost for development
    network_mode: host
    #ports:
    #  - "3000:3000"
    volumes:
      - telraam_grafana_storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
