version: "3.7"

volumes:
  telraam_grafana_storage: {}
  prometheus_data: {}
  loki_data: {}
  promtail_data: {}

services:
  timesync:
    build:
      context: timesync/
      dockerfile: Dockerfile
    network_mode: host
  prometheus:
    image: prom/prometheus:v2.42.0
    volumes:
      - ./prometheus/:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    network_mode: host
    depends_on:
      - blackbox
    # ports:
    #   - "9090:9090"
  blackbox:
    build:
      context: blackbox/
      dockerfile: Dockerfile
    network_mode: host
    # ports:
      # - "9115:9115"
  grafana:
    build:
      context: grafana
    user: "472"
    # depends_on:
    # - prometheus
    # Host network so grafana can query to localhost for development
    network_mode: host
    #ports:
    #  - "3000:3000"
    volumes:
      - telraam_grafana_storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
  loki:
    image: grafana/loki
    command: "-config.file /etc/loki/config.yaml"
    network_mode: host
    volumes:
      - ./loki:/etc/loki
      - loki_data:/loki
  promtail:
    image: grafana/promtail
    network_mode: host
    command: "-config.file /etc/promtail/config.yaml"
    volumes:
      - ./promtail:/etc/promtail
      - promtail_data:/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
