- targets:
    - $RONNY01_IP
  labels:
    service: station
    name: ronny01
    dbname: RONNY1
- targets:
    - $RONNY02_IP
  labels:
    service: station
    name: ronny02
    dbname: RONNY2
- targets:
    - $RONNY03_IP
  labels:
    service: station
    name: ronny03
    dbname: RONNY3
- targets:
    - $RONNY04_IP
  labels:
    service: station
    name: ronny04
    dbname: RONNY4
- targets:
    - $RONNY05_IP
  labels:
    service: station
    name: ronny05
    dbname: RONNY5
- targets:
    - $RONNY06_IP
  labels:
    service: station
    name: ronny06
    dbname: RONNY6
- targets:
    - $RONNY07_IP
  labels:
    service: station
    name: ronny07
    dbname: RONNY7
- targets:
    - $RONNY08_IP
  labels:
    service: station
    name: ronny08
    dbname: RONNY8
- targets:
    - $CLIENT1_IP
  labels:
    service: client1
    name: client1
- targets:
    - $CLIENT2_IP
  labels:
    service: client2
    name: client2
- targets:
    - 172.12.50.151
  labels:
    service: switch
    name: foh
- targets:
    - 172.12.50.152
  labels:
    service: switch
    name: crew
- targets:
    - 172.12.50.162
  labels:
    service: AP
    name: crew
- targets:
    - 172.12.50.163
  labels:
    service: AP
    name: C FOH
- targets:
    - 172.12.50.164
  labels:
    service: AP
    name: D
- targets:
    - 172.12.50.165
  labels:
    service: AP
    name: E IT
- targets:
    - 172.12.50.166
  labels:
    service: AP
    name: F
- targets:
    - 172.12.50.167
  labels:
    service: AP
    name: G
