- targets:
    - $RONNY01_IP
  labels:
    service: station
    name: ronny01
    dbname: RONNY1
- targets:
    - $RONNY02_IP
  labels:
    service: station
    name: ronny02
    dbname: RONNY2
- targets:
    - $RONNY03_IP
  labels:
    service: station
    name: ronny03
    dbname: RONNY3
- targets:
    - $RONNY04_IP
  labels:
    service: station
    name: ronny04
    dbname: RONNY4
- targets:
    - $RONNY05_IP
  labels:
    service: station
    name: ronny05
    dbname: RONNY5
- targets:
    - $RONNY06_IP
  labels:
    service: station
    name: ronny06
    dbname: RONNY6
- targets:
    - $RONNY07_IP
  labels:
    service: station
    name: ronny07
    dbname: RONNY7
- targets:
    - $RONNY08_IP
  labels:
    service: station
    name: ronny08
    dbname: RONNY8
- targets:
    - $CLIENT1_IP
  labels:
    service: client1
    name: client1
- targets:
    - $CLIENT2_IP
  labels:
    service: client2
    name: client2
- targets:
    - 172.12.50.140
  labels:
    service: AP
    name: IT
- targets:
    - 172.12.50.141
  labels:
    service: AP
    name: Crew
- targets:
    - 172.12.50.142
  labels:
    service: AP
    name: Bar
- targets:
    - 172.12.50.143
  labels:
    service: AP
    name: FOH
- targets:
    - 172.12.50.144
  labels:
    service: AP
    name: Buysse
- targets:
    - 172.12.50.145
  labels:
    service: AP
    name: bavet
- targets:
    - 172.12.50.150
  labels:
    service: switch
    name: IT
- targets:
    - 172.12.50.152
  labels:
    service: switch
    name: FOH
- targets:
    - 172.12.50.151
  labels:
    service: switch
    name: Crew
