global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: [ "localhost:9090" ]

  # - job_name: telraam
  #   metrics_path: /export
  #   static_configs:
  #     - targets: ["10.1.0.200:8080"]
  #
  - job_name: postgres.telraam_db
    metrics_path: /metrics
    static_configs:
      - targets: [ "$TELRAAM_IP:9187" ]

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    file_sd_configs:
      - files:
          - http_hosts.yml
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: "localhost:9115"

  - job_name: blackbox-ping
    metrics_path: /probe
    params:
      module: [ icmp ]
    file_sd_configs:
      - files:
          - ping_hosts.yml
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: "localhost:9115"

  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: [
          '$RONNY01_IP:9100',
          '$RONNY02_IP:9100',
          '$RONNY03_IP:9100',
          '$RONNY04_IP:9100',
          '$RONNY05_IP:9100',
          '$RONNY06_IP:9100',
          '$RONNY07_IP:9100',
          '$CLIENT1_IP:9100',
          '$CLIENT2_IP:9100'
        ]

rule_files:
  - "/etc/prometheus/*.rules"


#alerting:
#  alertmanagers:
#    - scheme: http
#      static_configs:
#        - targets:
#            - "localhost:9093"
