{
 "title": "network-traffic-ng",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uplink state",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{ifName=~\"ether10\"}",
     "legendFormat": "ABDIJ Link"
    },
    {
     "expr": "ifOperStatus{ifName=\"ether2\"}",
     "legendFormat": "4G Backup Link"
    }
   ]
  },
  {
   "title": "Uplink check",
   "type": "stat",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{ifName=\"ether10\"}[$__rate_interval])",
     "legendFormat": "ABDIJ Download"
    },
    {
     "expr": "rate(ifHCInOctets{ifName=\"ether2\"}[$__rate_interval])",
     "legendFormat": "4G Download"
    }
   ]
  },
  {
   "title": "Uplink Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{ifName=\"ether10\"}[$__rate_interval])",
     "legendFormat": "ABDIJ Download"
    },
    {
     "expr": "rate(ifHCOutOctets{ifName=\"ether10\"}[$__rate_interval]) * -1",
     "legendFormat": "ABDIJ Upload"
    },
    {
     "expr": "rate(ifHCInOctets{ifName=\"ether2\"}[$__rate_interval])",
     "legendFormat": "4G Download"
    },
    {
     "expr": "rate(ifHCOutOctets{ifName=\"ether2\"}[$__rate_interval]) * -1",
     "legendFormat": "4G Upload"
    }
   ]
  },
  {
   "title": "Crew/Bar Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{ifName=\"VLAN_100_CREW\"}[$__rate_interval])",
     "legendFormat": "CREW Download"
    },
    {
     "expr": "rate(ifHCInOctets{ifName=\"VLAN_100_CREW\"}[$__rate_interval]) * -1",
     "legendFormat": "CREW Upload"
    },
    {
     "expr": "rate(ifHCOutOctets{ifName=\"VLAN_110_BAR\"}[$__rate_interval])",
     "legendFormat": "BAR Download"
    },
    {
     "expr": "rate(ifHCInOctets{ifName=\"VLAN_110_BAR\"}[$__rate_interval]) * -1",
     "legendFormat": "BAR Upload"
    }
   ]
  },
  {
   "title": "Management/Telnet Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{ifName=\"VLAN_130_MGMT\"}[$__rate_interval])",
     "legendFormat": "MGMT Download"
    },
    {
     "expr": "rate(ifHCInOctets{ifName=\"VLAN_130_MGMT\"}[$__rate_interval]) * -1",
     "legendFormat": "MGMT Upload"
    },
    {
     "expr": "rate(ifHCOutOctets{ifName=\"VLAN_120_TELNET\"}[$__rate_interval])",
     "legendFormat": "TELNET Download"
    },
    {
     "expr": "rate(ifHCInOctets{ifName=\"VLAN_120_TELNET\"}[$__rate_interval]) * -1",
     "legendFormat": "TELNET Upload"
    }
   ]
  }
 ]
}