{
 "title": "Status Page",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "IT Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", service=\"telraam\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "probe_success{job=\"blackbox\", service=\"manualcount\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time Sync | Offsets",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.[*].name", "language": "jsonpath", "name": "", "type": "string" },
      { "jsonPath": "$.[*].abs_offset", "language": "jsonpath", "name": "", "type": "number" },
      { "jsonPath": "$.[*].success", "language": "jsonpath", "name": "", "type": "boolean" }
     ],
     "method": "GET",
     "urlPath": "/"
    }
   ]
  },
  { "title": "Stations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-ping\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Baton last seen",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.[*].time_since_seen", "type": "number" },
      { "jsonPath": "$.[*].name", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "urlPath": "/batons"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 14, "w": 3, "x": 9, "y": 10 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.[*]" }
     ],
     "method": "GET",
     "urlPath": "/batons"
    }
   ]
  },
  {
   "title": "Stations (network): current status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-ping\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Stations (web): current status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Stations (network): status over time",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-ping\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Stations (web): over time",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}