{
 "title": "Loxsi - Ronny",
 "tags": [
  "Loxsi",
  "Ronny"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Websocket connections to Loxsi",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Stations (network): current status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-ping\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Stations (web): current status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (count(*)/15.0) as count from detection where extract(epoch from timestamp) >= (extract(epoch from NOW() + interval '2 hour') - 15);"
    }
   ]
  },
  {
   "title": "Stations (web): over time",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Stations (network): status over time",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-ping\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Connections Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Station latest detection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "rawSql": "select EXTRACT(EPOCH FROM (now() - max(timestamp))), s.name\nfrom detection\n      right join station s on detection.station_id = s.id\ngroup by detection.station_id, s.id, s.name\norder by s.name;"
    }
   ]
  },
  {
   "title": "Ronny Detection count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select name, c from (select station_id, count(*) as c from detection GROUP BY detection.station_id) cs join station s on cs.station_id = s.id"
    }
   ]
  }
 ]
}