{
 "title": "Network Traffic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Router traffic IN",
   "type": "timeseries",
   "description": "Traffic on the mikrotik router per bridge network",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{ifName!~\"ether.*\"}[$__rate_interval])",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Router traffic OUT",
   "type": "timeseries",
   "description": "Traffic on the mikrotik router per bridge network",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{ifName!~\"ether.*\"}[$__rate_interval])",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "UplinkStatic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{ifName=\"uplinkStatic\"}[$__rate_interval])",
     "legendFormat": "InOctects"
    },
    {
     "expr": "-rate(ifHCOutOctets{ifName=\"uplinkStatic\"}[$__rate_interval])",
     "legendFormat": "OutOctets"
    }
   ]
  },
  {
   "title": "UplinkDHCP",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{ifName=\"uplinkDHCP\"}[$__rate_interval])",
     "legendFormat": "InOctects"
    },
    {
     "expr": "-rate(ifHCOutOctets{ifName=\"uplinkDHCP\"}[$__rate_interval])",
     "legendFormat": "OutOctets"
    }
   ]
  },
  {
   "title": "Switch Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{service=\"switch\", job=\"blackbox-ping\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AP Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{service=\"AP\", job=\"blackbox-ping\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "UplinkStatic (ucast)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifHCInUcastPkts{ifName=\"uplinkStatic\"}[$__rate_interval])",
     "legendFormat": "InOctects"
    },
    {
     "expr": "-rate(ifHCOutUcastPkts{ifName=\"uplinkStatic\"}[$__rate_interval])",
     "legendFormat": "OutOctets"
    }
   ]
  }
 ]
}