{
 "title": "Status Page",
 "time": { "from": "now-5m", "to": "now-2m" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "TEAM_NAME",
    "query": "select name as team_name from team"
   }
  ]
 },
 "panels": [
  {
   "title": "Client1",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-ping\", service=\"client1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AP Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{service=\"AP\", job=\"blackbox-ping\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Switch Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{service=\"switch\", job=\"blackbox-ping\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Station latest detection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "rawSql": "select EXTRACT(EPOCH FROM (now() - max(timestamp))), s.name\nfrom detection\n      right join station s on detection.station_id = s.id\ngroup by detection.station_id, s.id, s.name\norder by s.name;"
    }
   ]
  },
  {
   "title": "Battery percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (baton.name) name,\n       CASE\n           -- To see last battery not regarding time, chaneg seconds into years\n           WHEN (detection.timestamp >= now() - interval '60 SECONDS') THEN detection.battery\n       END\n       AS battery\nFROM detection right join baton ON baton.id = detection.baton_id\nORDER BY name, timestamp DESC, battery ASC"
    }
   ]
  },
  {
   "title": "Service status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", service=\"telraam\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "probe_success{job=\"blackbox\", service=\"manualcount\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "probe_success{job=\"blackbox\", service=\"livesite\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time Sync | Offsets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.[*].name", "language": "jsonpath", "name": "", "type": "string" },
      { "jsonPath": "$.[*].abs_offset", "language": "jsonpath", "name": "", "type": "number" },
      { "jsonPath": "$.[*].success", "language": "jsonpath", "name": "", "type": "boolean" }
     ],
     "method": "GET",
     "urlPath": "/"
    }
   ]
  },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- cursed query\nSELECT inner2.team_name AS team_name, s.coord_x AS lat, s.coord_y AS lon, s.name as dbname\nFROM (SELECT inner1.team_name AS team_name, d.station_id\n      FROM (SELECT t.name as team_name, MAX(d.timestamp) as timestamp\n            FROM detection d\n                     join team t on d.baton_id = t.baton_id\n                     join station s on d.station_id = s.id\n            WHERE t.name IN ([[TEAM_NAME]])\n            GROUP BY t.name) inner1\n               join detection d ON d.timestamp = inner1.timestamp) inner2\nright join station s on s.id = inner2.station_id"
    },
    {
     "expr": "probe_success{job=\"blackbox-ping\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Baton last seen",
   "type": "stat",
   "gridPos": { "h": 14, "w": 7, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "rawSql": "select EXTRACT(EPOCH FROM (now()-max(timestamp))) as since, b.name || ' (' || t.name || ')' as name\nfrom detection\n         right join baton b on b.id = detection.baton_id\n         right join team t on b.id = t.baton_id\ngroup by detection.baton_id, b.name, t.name"
    }
   ]
  },
  {
   "title": "Baton uptime/restarted",
   "type": "stat",
   "gridPos": { "h": 14, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select b.name, uptime_ms from (\n  SELECT distinct on (baton_id) baton_id, uptime_ms from detection  ORDER BY baton_id, timestamp DESC\n  ) d join baton b on d.baton_id = b.id join team t on d.baton_id = t.baton_id"
    }
   ]
  },
  {
   "title": "Stations (network): current status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-ping\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Stations (web): current status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Stations (network): status over time",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-ping\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Stations (web): over time",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", service=\"station\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 23 } },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 5, "x": 11, "y": 23 } },
  { "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 25 } }
 ]
}